language: node_js

node_js:
  - "6"

script:
  - npm test

after_success:
  - npm run version && npm build

before_deploy:
  - tar -czvf echo-vcap.tz . --exclude "node_modules" --exclude ".git" --exclude "echo-vcap.tz"

deploy:
  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file: "echo-vcap.tz"
    skip_cleanup: true
    on:
      branch: master
