language: node_js

node_js:
  - "6"

sudo: required

script:
  - npm test
  - ./debugenv.sh

after_success:
  - npm run version && npm build

env:
  global:
    ATLAS_TOKEN: token
  matrix:

deploy:
  - provider: atlas
    skip_cleanup: true
    metadata:
      - "custom_name=Jane"
      - "custom_surname=Doe"
    edge:
      source: adamkingit/dpl
      branch: cf-env
    on:
      branch: setenvs
  - provider: cloudfoundry
    api: "https://api.ng.bluemix.net"
    manifest: manifest-us-stage.yml
    username: $BLUEMIX_USER
    password: "notmypwd"
    organization: $BLUEMIX_ORG
    space: $BLUEMIX_SPACE
    skip_cleanup: true
    something_else: "is part of these options"
    cfenv:
      CF_REPO_SLUG: $TRAVIS_REPO_SLUG
      CF_COMMIT: $TRAVIS_COMMIT
      CF_COMMIT_RANGE: $TRAVIS_COMMIT_RANGE
    edge:
      source: adamkingit/dpl
      branch: cf-env
    on:
      branch: setenvs


  # - provider: script
  #   script: ./set_cf_env.sh echo-vcap-stage
  #   skip_cleanup: true
  #   on:
  #     branch: staging


  # - provider: cloudfoundry
  #   edge: true
  #   manifest: manifest-us-stage.yml
  #   username: $BLUEMIX_USER
  #   password: $BLUEMIX_PASSWORD
  #   api: "https://api.ng.bluemix.net"
  #   organization: $BLUEMIX_ORG
  #   space: $BLUEMIX_SPACE
  #   on:
  #     branch: staging
  # - provider: cloudfoundry
  #   edge: true
  #   manifest: manifest-us-beta.yml
  #   username: $BLUEMIX_USER
  #   password: $BLUEMIX_PASSWORD
  #   api: "https://api.ng.bluemix.net"
  #   organization: $BLUEMIX_ORG
  #   space: $BLUEMIX_SPACE
  #   on:
  #     condition: $TRAVIS_TAG = beta
  #     all_branches: true
  #     #branch: beta        #Travis uses that tag name as the branch name when the build is triggered by a tag.
  # - provider: cloudfoundry
  #   edge: true
  #   manifest: manifest-us-prod.yml
  #   username: $BLUEMIX_USER
  #   password: $BLUEMIX_PASSWORD
  #   api: "https://api.ng.bluemix.net"
  #   organization: $BLUEMIX_ORG
  #   space: $BLUEMIX_SPACE
  #   on:
  #     branch: master
  # - provider: cloudfoundry
  #   edge: true
  #   manifest: manifest-uk-prod.yml
  #   username: $BLUEMIX_USER
  #   password: $BLUEMIX_PASSWORD
  #   api: "https://api.eu-gb.bluemix.net"
  #   organization: $BLUEMIX_ORG
  #   space: $BLUEMIX_SPACE
  #   on:
  #     branch: master
