language: node_js

node_js:
  - "6"

script:
  - npm test

after_success:
  - npm run version && npm build

before_deploy:
  - mkdir -p tmp && tar -czvf tmp/echo-vcap.tz . --exclude "node_modules" --exclude ".git" --exclude "tmp"

deploy:
  - provider: script
    script: ./tagrelease.sh
    skip_cleanup: true
    on:
      branch: master

  - provider: releases
    api_key: "$GITHUB_OAUTH_TOKEN"
    file: "tmp/echo-vcap.tz"
    skip_cleanup: true
    on:
      branch: master
