language: node_js

node_js:
  - "6"

sudo: required

script:
  - npm test
  - ./debugenv.sh

after_success:
  - npm run version && npm build

env:
  global:

  matrix:

deploy:
  - provider: bluemixcloudfoundry
    manifest: manifest-us-stage.yml
    username: $BLUEMIX_USER
    password: $BLUEMIX_PASSWORD
    organization: $BLUEMIX_ORG
    space: $BLUEMIX_SPACE
    skip_cleanup: true
    on:
      branch: staging
  - provider: script
    script: ./set_cf_env.sh echo-vcap-stage
    skip_cleanup: true
    on:
      branch: staging

  # - provider: cloudfoundry
  #   edge: true
  #   manifest: manifest-us-stage.yml
  #   username: $BLUEMIX_USER
  #   password: $BLUEMIX_PASSWORD
  #   api: "https://api.ng.bluemix.net"
  #   organization: $BLUEMIX_ORG
  #   space: $BLUEMIX_SPACE
  #   on:
  #     branch: staging
  # - provider: cloudfoundry
  #   edge: true
  #   manifest: manifest-us-beta.yml
  #   username: $BLUEMIX_USER
  #   password: $BLUEMIX_PASSWORD
  #   api: "https://api.ng.bluemix.net"
  #   organization: $BLUEMIX_ORG
  #   space: $BLUEMIX_SPACE
  #   on:
  #     condition: $TRAVIS_TAG = beta
  #     all_branches: true
  #     #branch: beta        #Travis uses that tag name as the branch name when the build is triggered by a tag.
  # - provider: cloudfoundry
  #   edge: true
  #   manifest: manifest-us-prod.yml
  #   username: $BLUEMIX_USER
  #   password: $BLUEMIX_PASSWORD
  #   api: "https://api.ng.bluemix.net"
  #   organization: $BLUEMIX_ORG
  #   space: $BLUEMIX_SPACE
  #   on:
  #     branch: master
  # - provider: cloudfoundry
  #   edge: true
  #   manifest: manifest-uk-prod.yml
  #   username: $BLUEMIX_USER
  #   password: $BLUEMIX_PASSWORD
  #   api: "https://api.eu-gb.bluemix.net"
  #   organization: $BLUEMIX_ORG
  #   space: $BLUEMIX_SPACE
  #   on:
  #     branch: master
